name: Slack Workflow Notification
description: Send a message to Slack when a workflow completes

inputs:
  slack_token:
    description: 'Slack token'
    required: true
  slack_channel:
    description: 'Slack channel'
    required: true
  actor:
    description: The user who triggered the workflow
    required: true
  event:
    description: The event that triggered the workflow
    required: true
  conclusion:
    description: The conclusion of the workflow
    required: true
  env:
    description: The environment the workflow is related to
    required: true
  ref:
    description: The artifact reference (commit, tag, etc) of the workflow
    required: true
  workflow_id:
    description: The ID of the workflow that is being notified about
    required: true


runs:
  using: composite
  steps:
    - name: Context
      id:  context
      shell: bash
      run: |
        actor="${{ inputs.actor }}"
        event="${{ inputs.event }}"
        conclusion="${{ inputs.conclusion }}"
        env="${{ inputs.env }}"
        ref="${{ inputs.ref }}"

        if [[ "$conclusion" == "success" ]]; then
          emoji=":white_check_mark:"
        else
          emoji=":x:"
        fi

        workflow_id="${{ inputs.workflow_id }}"
        repo_url="${{ github.server_url }}/${{ github.repository }}"
        workflow_url="$repo_url/actions/runs/$workflow_id"

        message="$emoji [$env] $actor *$event* ($ref) completed with *$conclusion* $emoji"

        echo "message=${message}" >> $GITHUB_OUTPUT
        echo "workflow_id=${workflow_id}" >> $GITHUB_OUTPUT
        echo "workflow_url=${workflow_url}" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

    - name: Notify Slack
      uses: mozilla/addons/.github/actions/slack@main
      with:
        slack_token: ${{ inputs.slack_token }}
        method: chat.postMessage
        payload: |
          channel: "${{ inputs.slack_channel }}"
          text: "${{ steps.context.outputs.message }}"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "${{ steps.context.outputs.message }}"
            - type: actions
              elements:
                - type: button
                  text:
                    type: plain_text
                    text: "View Workflow (${{ steps.context.outputs.workflow_id }})"
                    emoji: true
                  value: workflow_url
                  url: "${{ steps.context.outputs.workflow_url }}"
