version: '3.8'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - node_modules:/app/node_modules
      - dist:/app/dist
      - .:/app:delegated
    command: npm run dev
    ports:
      - 3000:3000

volumes:
  node_modules:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/node_modules"
  dist:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/dist"
