name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type:bug", "needs:info"]
type: bug
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include in detailed steps how to reproduce the bug you encountered
      placeholder: |
        Make sure that you include all of the detailed steps
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Include details
      placeholder: |
        What did you think was going to happen when you noticed the bug?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing [bugs](https://github.com/mozilla/test-github-features/issues?q=is%3Aopen+is%3Aissue+label%3Atype%3Abug)
        required: true
