name: Task
description: Filing a task (contributors only)
title: "[Task]: "
labels: ["type:feature", "needs:info"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A few sentences describing what the task aims to achieve.
        It can be a simple sentence or a story formatted paragraph.
        Be concise and detailed. Avoid vague terms and include relevant links.
      placeholder: As a <blank>, I want to <blank, so that I can <blank>
    validations:
      required: true

  - type: dropdown
    id: repositories
    attributes:
      label: What repositories are related to this task?
      multiple: true
      options:
        - addons-server
        - addons-frontend