name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  tag:
    description: 'The docker image tag to run.'
    required: true
  run:
    description: 'Run command in container'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v4
      with:
        # The artifact name should be kept in sync with
        # ./.github/actions/build/action.yml which uploads the artifact
        name: docker-image
        path: /tmp/

      # image.tar is the name of the compressed image file
      # This should be kept in sync with ./.github/actions/build/action.yml
    - name: Load image
      shell: bash
      run: |
        docker load < /tmp/image.tar
        docker image ls

    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_TAG: ${{ inputs.tag }}
      run: |
        # Start the specified services
        make up

        # Exec the run command in the container
        # quoted 'EOF' to prevent variable expansion
        cat <<'EOF' | docker compose exec --user root app sh
          #!/bin/bash
          whoami
          ${{ inputs.run }}
        EOF
