name: 'Docker Push image to registry'
description: 'Pushes build docker image to registry'
inputs:
  tag:
    required: true
    description: "The full docker tag to push"
  password:
    required: false
    description: "Password for the registry"
  username:
    required: false
    description: "Username for the registry"
  registry:
    required: false
    description: "The registry to push to"
    default: "ghcr.io"

runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push Image
      shell: bash
      run: |
        docker image push ${{ inputs.registry }}/${{ inputs.tag }}
