name: Default (completed)

on:
  workflow_run:
    workflows: 'Default'
    types:
      - completed

jobs:
  context:
    runs-on: ubuntu-latest

    outputs:
      is_release_master: true
      is_release_tag: true

    steps:
      - uses: actions/checkout@v4

  notify_slack:
    runs-on: ubuntu-latest
    needs: [context]
    # Only notify slack on release events
    if: ${{ needs.context.outputs.is_release_master || needs.context.outputs.is_release_tag }}
    steps:
      - name: Notify Slack
        uses: mozilla/addons/.github/actions/slack@main
        env:
          retry_text: '[Rerun Workflow](${{ github.event.workflow_run.rerun_url }})'
          event_text: ${{ needs.context.outputs.is_release_master && 'Release Master' || 'Release Tag' }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_ADDONS_PRODUCTION_CHANNEL }}
          message: test
