name: Default (completed)

on:
  workflow_run:
    workflows: 'Default'
    types:
      - completed

jobs:
  context:
    runs-on: ubuntu-latest

    outputs:
      is_release_master: true
      is_release_tag: true

    steps:
      - uses: actions/checkout@v4

  notify_slack:
    runs-on: ubuntu-latest
    needs: [context]
    # Only notify slack on release events
    if: ${{ needs.context.outputs.is_release_master || needs.context.outputs.is_release_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./.github/actions/slack
        env:
          retry_text: '[Rerun Workflow](${{ github.event.workflow_run.rerun_url }})'
          event_text: ${{ needs.context.outputs.is_release_master && 'Release Master' || 'Release Tag' }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          method: chat.postMessage
          payload: |
            channel: ${{ secrets.SLACK_ADDONS_PRODUCTION_CHANNEL }}
            blocks:
              - type: context
                elements:
                  - type: mrkdwn
                    text: ":github: *Workflow Run:* ${{ github.event.workflow_run.url }}"
