name: Default (completed)

on:
  workflow_run:
    workflows: ['Default', 'Release']
    types:
      - completed

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/context

  slack_notification:
    needs: context
    strategy:
      matrix:
        include:
          - actor: ${{ github.event.workflow_run.actor.login }}
            event: 'push'
            conclusion: 'success'
            env: 'dev'
            ref: ${{ github.event.workflow_run.head_commit.id }}
          - actor: ${{ github.event.workflow_run.actor.login }}
            event: 'push'
            conclusion: 'failure'
            env: 'dev'
            ref: ${{ github.event.workflow_run.head_commit.id }}
          - actor: ${{ github.event.workflow_run.actor.login }}
            event: 'release'
            conclusion: 'success'
            env: 'production'
            ref: 2025.01.01
          - actor: ${{ github.event.workflow_run.actor.login }}
            event: 'release'
            conclusion: 'failure'
            env: 'production'
            ref: 2025.01.01

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack-workflow-notification
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: ${{ secrets.SLACK_ADDONS_PRODUCTION_CHANNEL }}
          actor: ${{ matrix.actor }}
          event: ${{ matrix.event }}
          conclusion: ${{ matrix.conclusion }}
          env: ${{ matrix.env }}
          ref: ${{ matrix.ref }}
          workflow_id: ${{ github.event.workflow_run.id }}
