name: Default (completed)

on:
  workflow_run:
    workflows: 'Default'
    types:
      - completed

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/context

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
