name: Deploy

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - id: environment
        shell: bash
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "ref: ${{ github.ref }}"

          environment=""
          url=""

          if [[ "${{ github.event_name }}" == 'push' ]]; then
            environment=production"
            url=https://test-github-features.fly.dev"
          elif [[ "${{ github.event_name }}" == 'merge_group' ]]; then
            environment=staging"
            url=https://test-github-features-staging.fly.dev"
          elif [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
            environment=development"
            url=https://test-github-features-staging.fly.dev"
          fi

          echo "environment=$environment" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
  deploy:
    needs: environment
    if: ${{ needs.environment.outputs.environment }}
    environment:
      name: ${{ needs.environment.outputs.environment }}
      url: ${{ needs.environment.outputs.environment }}.example.com
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: ./.github/actions/build
        with:
          push: true
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          config: ${{ github.workspace }}/fly-${{ needs.environment.outputs.environment}}.toml
          token: ${{ secrets.FLY_TOKEN }}
          image: ${{ steps.build.outputs.tags }}
      - id: pr_url
        shell: bash
        run: |
          echo "url=${{ github.repositoryUrl }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
      - name: Notify (scuccessful deployment)
        if: success()
        uses: ./.github/actions/slack
        with:
          message: ":tada: Successfully deployed to ${{ env.environment }} :white_check_mark:! <${{ steps.pr_url.outputs.url }}>"
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify (failed deployment)
        if: failure()
        uses: ./.github/actions/slack
        with:
          message: ":fail: Failed to deploy to ${{ env.environment }} :red_flag:! <${{ steps.pr_url.outputs.url }}>"
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
