name: Deploy (production)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.event_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://test-github-features.fly.dev
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: ./.github/actions/build
        with:
          push: true
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: production
          image: ${{ steps.build.outputs.image_version }}
          fly_token: ${{ secrets.FLY_TOKEN }}
