name: On Deployment

on:
  deployment_status:

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/context
      - name: Get The PRs associated with the commit
        id: prs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          data=$(gh api graphql \
            -F owner='${{ github.repository_owner }}' \
            -F name='${{ github.event.repository.name }}' \
            -F ref='${{ github.sha }}' \
            -F query='query($name: String!, $owner: String!, $ref: GitObjectID!) {
                repository(owner: $owner, name: $name) {
                  object(oid: $ref) {
                    ...on Commit {
                      associatedPullRequests(first: 10) {
                        nodes {
                          number
                        }
                      }
                    }
                  }
                }
              }')

          prs=$(echo $data | jq -r '.data.repository.object.associatedPullRequests.nodes[].number')

          echo "prs=$prs" >> $GITHUB_OUTPUT
          echo "prs $prs"
          echo "data $data"

      - name: Create Comment Text
        id: comment
        shell: bash
        run: |
          environment='${{ github.event.deployment_status.environment}}'
          environment_url='${{ github.event.deployment_status.environment_url }}'
          commit_url='${{ github.server_url}}/${{ github.repository}}/commit/${{ github.sha }}'
          created_at='${{ github.event.deployment_status.created_at }}'
          updated_at='${{ github.event.deployment_status.updated_at }}'
          log_url='${{ github.event.deployment_status.log_url }}'

          cat <<EOF >> comment.txt
          This PR was shipped:
          - environment: $environment
          - environment url: <$environment_url>
          - commit url: <$commit_url>
          - created at: $created_at
          - updated at: $updated_at
          - log url: <$log_url>
          EOF

          echo "text=$(cat comment.txt)" >> $GITHUB_OUTPUT

      - name: Comment PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          for pr in $(echo '${{ steps.prs.outputs.prs }}'); do
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository }}/pulls/$pr/reviews \
              -f body="$(cat ${{ steps.comment.outputs.text }})" \
              -F event=COMMENT
          done
