name: Deploy (staging)

on:
  merge_group:

concurrency:
  group: ${{ github.event_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://test-github-features-staging.fly.dev
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: ./.github/actions/build
        with:
          push: true
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          node_env: production

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: staging
          image: ${{ steps.build.outputs.image_version }}
          fly_token: ${{ secrets.FLY_TOKEN }}
