name: On Deployment

on:
  deployment

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/context
      - name: Get The PRs associated with the commit
        id: prs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          data=$(gh api graphql \
            -F owner='${{ github.repository_owner }}' \
            -F name='${{ github.event.repository.name }}' \
            -F ref='${{ github.sha }}' \
            -F query='query($name: String!, $owner: String!, $ref: GitObjectID!) {
                repository(owner: $owner, name: $name) {
                  object(oid: $ref) {
                    ...on Commit {
                      associatedPullRequests(first: 10) {
                        nodes {
                          number
                        }
                      }
                    }
                  }
                }
              }')

          prs=$(echo $data | jq -r '.data.repository.object.associatedPullRequests.nodes[].number')

          echo "prs=$prs" >> $GITHUB_OUTPUT
          echo "prs $prs"
          echo "data $data"

      - name: Get Deployment statuses
        id: status
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          data=$(gh api \
            /repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses)

          echo "statuses=$(echo $data | jq -r '.[] | "- \(.state) - \(.updated_at) to \(.environment_url)"')" >> $GITHUB_OUTPUT

      - name: Comment PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          environment='${{ github.event.deployment.environment}}'
          repository_url='${{ github.event.deployment.repository_url }}'

          cat <<EOF >> comment.txt
          This PR was shipped at ${{ github.event.deployment.created_at }}
          - environment: $environment
          - commit: [${{ github.sha }}]($repository_url/commit/${{ github.sha }})
          - action run url: ${{ github.event.deployment.url }}

          statuses:
            ${{ steps.status.outputs.statuses }}
          EOF

          for pr in $(echo '${{ steps.prs.outputs.prs }}'); do
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository }}/pulls/$pr/reviews \
              -f body="$(cat comment.txt)" \
              -F event=COMMENT
          done
