name: On Deployment

on:
  deployment:
  deployment_status:

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/context
      - name: Get The PRs associated with the commit
        id: prs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          data=$(gh api graphql \
            -F owner='${{ github.repository_owner }}' \
            -F name='${{ github.event.repository.name }}' \
            -F ref='${{ github.sha }}' \
            -F query='query($name: String!, $owner: String!, $ref: GitObjectID!) {
                repository(owner: $owner, name: $name) {
                  object(oid: $ref) {
                    ...on Commit {
                      associatedPullRequests(first: 10) {
                        nodes {
                          number
                        }
                      }
                    }
                  }
                }
              }')

          prs=$(echo $data | jq -r '.data.repository.object.associatedPullRequests.nodes[].number')

          echo "prs=$prs" >> $GITHUB_OUTPUT
          echo "prs $prs"
          echo "data $data"

      - name: Get Environment Information
        id: environment
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          environment=$(
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/environments/${{ github.event.deployment.environment}}
          )

          echo "html_url=$(echo $environment | jq -r '.html_url')" >> $GITHUB_OUTPUT

      - name: Comment PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          environment='${{ github.event.deployment.environment}}'
          repository_url='${{ github.server_url}}/${{ github.repository}}'

          cat <<EOF >> comment.txt
          This PR was shipped at ${{ github.event.deployment.created_at }}
          - environment: $environment
          - url: ${{ steps.environment.outputs.html_url }}
          - commit: [${{ github.sha }}]($repository_url/commit/${{ github.sha }})
          - action run url: ${{ github.event.workflow_run.html_url }}
          EOF

          for pr in $(echo '${{ steps.prs.outputs.prs }}'); do
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/${{ github.repository }}/pulls/$pr/reviews \
              -f body="$(cat comment.txt)" \
              -F event=COMMENT
          done
