name: merge queueu
on:
  pull_request:
  merge_group:
jobs:
  merge_build:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm run build
      env:
        CI_DELAY: "10000"
        CI_FAIL: ""
