name: merge queueu
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - gh-readonly-queue/main/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm run build
      env:
        CI_DELAY: "60000"
        CI_FAIL: "1"
