name: Ping slack

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/slack
        with:
          message: 'Hello from GitHub Actions! :tada:'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
