name: Publish

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to registry'
        required: false
        default: 'false'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      id: build
      uses: ./.github/actions/build
      with:
        push: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify (success)
      if: success()
      uses: ./.github/actions/slack
      with:
        message: "Image built and pushed to https://github.com/mozilla/test-github-features/pkgs/container/test-github-features ${{ steps.build.outputs.tags }}"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Notify (failure)
      if: failure()
      uses: ./.github/actions/slack
      with:
        message: "Image build failed for ${{ github.repositoryUrl}}/runs/${{ github.run_number }}"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

