name: Worker (fork)

on:
  workflow_call:
    inputs:
      boolean:
        description: 'A boolean input'
        default: true
        required: true
        type: boolean
      number:
        description: 'A number input'
        default: 0
        required: true
        type: number
      string:
        description: 'A string input'
        default: 'foo'
        required: true
        type: string
      optional:
        description: 'An optional input'
        default: 'fallback'
        required: false
        type: string
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.output.outputs.one }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.output.outputs.two }}
    secrets:
      token:
        description: 'A token passed from the caller workflow'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/context

  secret:
    env:
      github_secret: ${{ github.event.workflow_call.secrets.token }}
      secret: ${{ secrets.token }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          set -x
          echo "secrets.token ${{ secrets.token }}"
          echo "env.secret: ${{ env.secret }}"
          echo "contains(env, 'secret'): ${{ contains(env, 'secret') }}"
          echo "env.github_secret: ${{ env.github_secret }}"
          echo "contains(env, 'github_secret'): ${{ contains(env, 'github_secret') }}"

  output:
    runs-on: ubuntu-latest

    outputs:
      one: ${{ steps.output.outputs.big }}
      two: ${{ steps.test.outcome }}
    steps:
      - uses: actions/checkout@v4
      - id: output
        shell: bash
        run: |
          echo "big=${{ inputs.number > 10 }}" >> $GITHUB_OUTPUT
      - id: test
        shell: bash
        run: |
          if [[ "${{ inputs.boolean }}" == 'true' ]]; then
            exit 1
          fi


